#### SEML and SLURM config

seml:
  executable: main.py
  name: EML_Project
  conda_environment: /csghome/eml01/project/envs
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter
    partition: exercise-eml
    gres: gpu:1


#### Experiment config

fixed:
  general:
    num_epochs: 1
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: CIFAR10
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
    LeNet:
      conf_name: LeNet5-BN
  noise_settings.default.noise_type: NoNoise
  noise_settings.layer_wise:
    layer_index: 5
    enable_in_training: 1

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 1
    step: 1

gauss_combined_zoomed_lin:
  fixed:
    noise_settings.layer_wise:
      noise_type: GaussCombined_direct
      FirstMulThenAdd: True
      GaussMeanMul: 1.0
      GaussMeanAdd: 0.0
  grid:
    noise_settings.layer_wise:
      GaussStdMul:
        type: loguniform
        min: 1e-4
        max: 1e+13
        num: 10
      GaussStdAdd:
        type: loguniform
        min: 1e-4
        max: 1e+13
        num: 10

